doc.go
provider/provider.go
server/handlers.go
server/openapi.go
server/routes.go

Per subject, plus small gofmt fixes.

add support for /api/conformance

---

main.go

Will add extra logic for postgresql data providers once supported

implement -d flag (#27)

---

data_provider/provider.go
server/handlers.go
server/handlers_internal_test.go
wfs3/features.go

Added support for a time parameter.
Currently limited to recognizing specific properties "start_time", "stop_time", "timestamp".
Resolves #50

Time parameter

---

server/handlers.go
server/handlers_internal_test.go

Rename 'pageSize' query param -> 'limit'. (#49)

---

.gitignore
.travis.yml
Gopkg.toml
README.md

Set up dependency versioning w/ go dep.  Added .travis.yml.

Add automated travis builds.

---

server/handlers.go
server/handlers_internal_test.go
wfs3/features.go
wfs3/wfs3_types.go

Resolves #65
Check the note on `timeStamp` and let me know if I'm missing something in the spec.

Add 'numberMatched' & 'numberReturned' to feature collection return.

---

data_provider/provider.go
server/handlers.go
server/handlers_internal_test.go
wfs3/features.go
wfs3/wfs3_types.go

Restore host:port portion of links. (#79)

---

config/config.go
server/handlers.go
server/handlers_internal_test.go

Add collections meta data alternate link(s) for supported MIME types.

---

config/config.go
server/handlers.go
server/handlers_internal_test.go
wfs3/openapi3.go

Add limit default, min, max to openapi3 schema. (#88)

---

data_provider/provider.go
server/handlers.go
server/handlers_internal_test.go
wfs3/features.go
wfs3/openapi3.go

Add property filters as query parameters in collection data requests.

---

server/handlers.go
util/util.go
util/util_test.go
wfs3/html_templates.go
wfs3/wfs3_types.go

Initial draft of HTML representation.  Notes:
- OL4 is provided as an external dependency for the time being

implement HTML representation

---

server/handlers.go
server/handlers_internal_test.go

Accurate absolute links in responses.

---

Gopkg.toml
README.md
server/handlers.go
server/handlers_internal_test.go
server/server_awslambda.go
wfs3/features.go
wfs3/openapi3.go

Adds support for AWS Lambda deployments by compiling with "awslambda" flag.

Lambda Support

---

server/handlers_internal_test.go
wfs3/collection_meta_data.go
wfs3/wfs3_types.go

Add "text/html" links for each collection to collection metadata. (#82)

---

wfs3/html_templates.go

fix HTML links (#103)

---

.gitignore
server/handlers.go
server/handlers_internal_test.go
wfs3/collection_meta_data.go

Change alternate type links in /collections/{cname} to ref='alternate'. (#82)

---

.gitignore
wfs3/html_templates.go

Eliminated html version of api link in html root. (#105)

---

.gitignore
server/handlers.go
server/handlers_internal_test.go
wfs3/root.go
wfs3/wfs3_types.go

Add rel='alternate' link to root content.

---

server/handlers.go
server/handlers_internal_test.go

Add 'item' links to single collection metadata. (#106)

---

server/handlers.go
server/handlers_internal_test.go
wfs3/collection_meta_data.go
wfs3/wfs3_types.go

Also refactored so query parameters in urls are in consistent (lexical) order.
Resolves #112

Add 'alternate' links to .../items/ endpoint (#112).

---

server/handlers.go
server/handlers_internal_test.go
wfs3/wfs3_types.go

Add 'alternate' links to single-feature responses. (#113)

---

server/handlers.go
wfs3/html_templates.go

add collection link and paging to HTML
